package at.smiech.cyanbat.desktop

import java.awt.image.BufferedImage
import javax.imageio.ImageIO

/**
 * The CyanBat icon as a running window shows it: in the title bar, and on the task bar button on
 * Windows and Linux. macOS draws no icon on a window; its Dock takes the installer's.
 *
 * Every size is its own file, generated by tools/generate_icons.py, because the platform picks the
 * size it needs from the list and only scales when the list has nothing close. Compose's own icon
 * parameter hands over a single 192px image instead, which Windows shrinks to 16px itself, and at
 * that ratio pixel art turns to noise.
 *
 * The installers carry the icon in each platform's own format; see nativeDistributions in
 * build.gradle.kts.
 */
internal object WindowIcon {
    /** Every size generated, smallest first; DESKTOP_SIZES in the generator. */
    val SIZES = listOf(16, 20, 24, 32, 40, 48, 64, 96, 128, 256)

    /** The icon at each of [SIZES], read on first use. */
    val images: List<BufferedImage> by lazy { SIZES.map(::load) }

    private fun load(size: Int): BufferedImage {
        val name = "/icons/cyanbat_$size.png"
        val stream = javaClass.getResourceAsStream(name)
            ?: error("Icon <$name> not found on the classpath")
        return stream.use { ImageIO.read(it) } ?: error("Icon <$name> did not decode as an image")
    }
}
