import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    alias(libs.plugins.kotlinJvm)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.composeMultiplatform)
}

kotlin {
    jvmToolchain(libs.versions.jvmToolchain.get().toInt())
}

sourceSets {
    // The same asset files the Android app packages; here they ride along as classpath resources.
    main { resources.srcDir(rootProject.file("assets")) }

    // The recorder behind the README's gameplay GIF; see recordGameplay below. Its own source
    // set, so none of it ships in the app, but built on the app's classes and classpath, so it
    // hosts the game exactly as the window does.
    val recorder = create("recorder") {
        compileClasspath += main.get().output
        runtimeClasspath += main.get().output
    }

    // Its tests sit with the app's, which is also what has every build compile it.
    test {
        compileClasspath += recorder.output
        runtimeClasspath += recorder.output
    }
}

configurations["recorderImplementation"].extendsFrom(configurations.implementation.get())
configurations["recorderRuntimeOnly"].extendsFrom(configurations.runtimeOnly.get())

dependencies {
    implementation(project(":game"))
    testImplementation(libs.kotlin.test.junit)
    implementation(compose.desktop.currentOs)
    implementation(libs.kotlinx.coroutines.core)
    // Provides Dispatchers.Main on the JVM, backed by the Swing event queue.
    implementation(libs.kotlinx.coroutines.swing)
}

// Flies every stage on an autopilot, headless and faster than real time, and writes one reel of
// them to docs/gameplay.gif. Arguments pass through:
// --args="--stages=2 --out=build/cave.gif --frames=build/frames".
tasks.register<JavaExec>("recordGameplay") {
    group = "documentation"
    description = "Records the README's gameplay GIF by flying each stage on an autopilot."
    classpath = sourceSets["recorder"].runtimeClasspath
    mainClass = "at.smiech.cyanbat.desktop.recorder.RecordGameplayKt"
    workingDir = rootDir
    jvmArgs("-Djava.awt.headless=true", "--enable-native-access=ALL-UNNAMED")
    maxHeapSize = "2g"
}

compose.desktop {
    application {
        // Skia loads its native library through System.load, which the JDK warns about otherwise.
        jvmArgs += "--enable-native-access=ALL-UNNAMED"
        mainClass = "at.smiech.cyanbat.desktop.MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "CyanBat"
            // jpackage insists on major.minor.patch; see the root build.gradle.kts.
            packageVersion = rootProject.extra["cyanbatPackageVersion"] as String
            // Each installer takes the icon in its own platform's format, all three generated by
            // tools/generate_icons.py; without them the plugin packages its default, the Kotlin logo.
            // On macOS the run task hands the .icns to the Dock too. The window sets its own; see
            // WindowIcon.
            macOS { iconFile.set(project.file("icons/cyanbat.icns")) }
            windows { iconFile.set(project.file("icons/cyanbat.ico")) }
            linux { iconFile.set(project.file("icons/cyanbat.png")) }
        }
    }
}
